/**
 * setup-local.mjs — 本机一键配置（Windows 任务计划程序 + headless profile + 运行文件）
 *
 * 面板里点「一键配置本机」后做的事情：
 *   1. 安装运行文件到 ~/.dsh/dsh-report-scheduler（带版本戳，插件升级后自动覆盖）
 *   2. 确保 headless profile 存在（不存在则用 dsh plugin add 创建并安装 bundle）
 *   3. 生成 tick.cmd（把本机 node / DSH_HOME / 目录写成绝对路径）
 *   4. 注册 Windows 计划任务（默认每 15 分钟，隐藏窗口）
 */
import { spawn } from 'node:child_process';
import { cp, mkdir, readFile, writeFile, access, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { RUNTIME_DIR, detectPaths, profileDir } from './paths.mjs';

export const DEFAULT_TASK_NAME = 'DSH-Report-Dispatcher';
/** 旧版本用过的任务名，用于识别已存在的任务 */
export const LEGACY_TASK_NAMES = ['DSH-Report-Tick'];
/** 每次 tick 交给 dispatcher 判断是否到点（分钟） */
export const DEFAULT_INTERVAL_MINUTES = 15;

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

/** 跑一个子进程并回收输出。 */
function run(command, args, { timeoutMs = 300000, cwd } = {}) {
  return new Promise((resolve) => {
    const child = spawn(command, args, { windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'], ...(cwd ? { cwd } : {}) });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (c) => { stdout += c.toString('utf8'); });
    child.stderr.on('data', (c) => { stderr += c.toString('utf8'); });
    const timer = setTimeout(() => child.kill(), timeoutMs);
    child.on('error', (error) => {
      clearTimeout(timer);
      resolve({ code: -1, stdout, stderr: String(error) });
    });
    child.on('close', (code) => {
      clearTimeout(timer);
      resolve({ code, stdout, stderr });
    });
  });
}

/** 插件自带运行文件的版本号（VERSION 文件内容）。 */
export async function runtimeVersion() {
  try {
    return (await readFile(join(RUNTIME_DIR, 'VERSION'), 'utf8')).trim();
  } catch {
    return '0';
  }
}

/** 把插件里的运行文件安装到 schedDir；版本没变就跳过。 */
export async function ensureRuntime(schedDir, { force = false } = {}) {
  const want = await runtimeVersion();
  const stampPath = join(schedDir, '.runtime-version');
  let have = '';
  try {
    have = (await readFile(stampPath, 'utf8')).trim();
  } catch { /* 首次安装 */ }
  if (!force && have === want) return { ok: true, installed: false, version: want };

  await mkdir(schedDir, { recursive: true });
  const files = ['run-report.mjs', 'dispatcher.mjs', 'hidden-run.vbs'];
  for (const file of files) {
    await cp(join(RUNTIME_DIR, file), join(schedDir, file));
  }
  await writeFile(stampPath, `${want}\n`, 'utf8');
  return { ok: true, installed: true, version: want, files };
}

/** 生成 tick.cmd：把本机路径写死，避免每次都要探测。
 *  注释保持纯 ASCII：cmd.exe 用 OEM 代码页读批处理文件，中文 UTF-8 会变乱码。 */
function tickCmdBody({ schedDir, dshHome, node }) {
  return [
    '@echo off',
    'rem DSH report scheduler - tick entry (called by Windows Task Scheduler)',
    'rem Generated by the dsh-report-scheduler plugin. Delete it and re-run "setup this machine" in the panel to regenerate.',
    `set "DSH_HOME=${dshHome}"`,
    `set "SCHED=${schedDir}"`,
    `set "NODE=${node}"`,
    '',
    'echo. >> "%SCHED%\\tick.out.log"',
    'echo ===== tick %DATE% %TIME% ===== >> "%SCHED%\\tick.out.log"',
    '"%NODE%" "%SCHED%\\dispatcher.mjs" >> "%SCHED%\\tick.out.log" 2>&1',
    'exit /b %ERRORLEVEL%',
    '',
  ].join('\r\n');
}

/** 用 PowerShell 读任务详情（JSON，避免中文控制台编码问题）。 */
async function taskDetails(name) {
  const safe = String(name).replace(/['"`$]/g, '');
  const script = [
    '$ErrorActionPreference = "Stop";',
    `$t = Get-ScheduledTask -TaskName '${safe}';`,
    `$i = Get-ScheduledTaskInfo -TaskName '${safe}';`,
    '[pscustomobject]@{ State = [string]$t.State; LastRunTime = [string]$i.LastRunTime; NextRunTime = [string]$i.NextRunTime; LastTaskResult = $i.LastTaskResult } | ConvertTo-Json -Compress',
  ].join(' ');
  const res = await run('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', script], { timeoutMs: 40000 });
  if (res.code !== 0) return undefined;
  try {
    const parsed = JSON.parse(res.stdout.trim().split(/\r?\n/).pop() ?? '');
    return {
      status: parsed.State,
      lastRun: parsed.LastRunTime && parsed.LastRunTime !== '0001/1/1 0:00:00' ? parsed.LastRunTime : undefined,
      nextRun: parsed.NextRunTime && parsed.NextRunTime !== '0001/1/1 0:00:00' ? parsed.NextRunTime : undefined,
      lastResult: parsed.LastTaskResult === undefined ? undefined : String(parsed.LastTaskResult),
    };
  } catch {
    return undefined;
  }
}

/** 查询计划任务是否存在（Windows）；优先查配置的名字，再查历史名字。 */
export async function schtaskStatus(taskName = DEFAULT_TASK_NAME, node = process.execPath) {
  if (process.platform !== 'win32') return { supported: false, exists: false };
  for (const name of [taskName, ...LEGACY_TASK_NAMES.filter((n) => n !== taskName)]) {
    const res = await run('schtasks.exe', ['/Query', '/TN', name, '/FO', 'LIST'], { timeoutMs: 30000 });
    if (res.code !== 0) continue;
    const details = await taskDetails(name);
    return { supported: true, exists: true, name, legacy: name !== taskName, detail: undefined, ...(details ?? {}) };
  }
  return { supported: true, exists: false, detail: `未找到计划任务「${taskName}」` };
}

/** 注册/注销计划任务。 */
export async function schtaskCommand(action, { taskName = DEFAULT_TASK_NAME, vbsPath, intervalMinutes = DEFAULT_INTERVAL_MINUTES }) {
  if (process.platform !== 'win32') {
    return { ok: false, error: '当前系统不是 Windows，本机定时请用系统自带的 cron 调用 dispatcher.mjs' };
  }
  if (action === 'create') {
    const res = await run('schtasks.exe', [
      '/Create', '/TN', taskName,
      '/TR', `wscript.exe "${vbsPath}"`,
      '/SC', 'MINUTE', '/MO', String(intervalMinutes),
      '/F',
    ], { timeoutMs: 60000 });
    return { ok: res.code === 0, detail: (res.stdout || res.stderr).trim().slice(0, 300) };
  }
  if (action === 'delete') {
    const res = await run('schtasks.exe', ['/Delete', '/TN', taskName, '/F'], { timeoutMs: 60000 });
    return { ok: res.code === 0, detail: (res.stdout || res.stderr).trim().slice(0, 300) };
  }
  if (action === 'run') {
    const res = await run('schtasks.exe', ['/Run', '/TN', taskName], { timeoutMs: 60000 });
    return { ok: res.code === 0, detail: (res.stdout || res.stderr).trim().slice(0, 300) };
  }
  return { ok: false, error: `未知动作 ${action}` };
}

/**
 * 一键配置本机。
 * @param {object} options
 * @param {string} options.schedDir                运行目录（~/.dsh/dsh-report-scheduler）
 * @param {string} [options.profile]               无头 profile 名，默认 headless
 * @param {string} [options.taskName]              计划任务名
 * @param {number} [options.intervalMinutes]       tick 间隔
 * @param {boolean} [options.registerTask]         是否注册计划任务（默认 true）
 * @param {(log:string)=>void} [options.onLog]     进度回调
 */
export async function setupLocal(options) {
  const {
    schedDir,
    profile = 'headless',
    taskName = DEFAULT_TASK_NAME,
    intervalMinutes = DEFAULT_INTERVAL_MINUTES,
    registerTask = true,
    onLog,
  } = options;

  const steps = [];
  const step = (name, ok, detail) => {
    steps.push({ name, ok, detail: detail === undefined ? undefined : String(detail).slice(0, 400) });
    onLog?.(`${ok ? '✓' : '✗'} ${name}${detail ? ' — ' + String(detail).slice(0, 160) : ''}`);
    return ok;
  };

  const paths = await detectPaths();
  if (!paths.node) return { ok: false, error: '找不到 node 可执行文件（DSH 自带的 node 或系统 node 都可以）', steps, paths };
  if (!paths.dshCli) return { ok: false, error: '找不到 DSH CLI（bin.js）；请在 DSH Desktop 里使用本插件', steps, paths };
  step('探测本机环境', true, `node=${paths.node}（${paths.nodeKind}）DSH_HOME=${paths.dshHome}`);

  // 1) 运行文件
  const runtime = await ensureRuntime(schedDir, { force: true });
  step('安装运行文件', runtime.ok, `版本 ${runtime.version} → ${schedDir}`);

  // 2) headless profile
  const pDir = profileDir(paths.dshHome, profile);
  const manifest = join(pDir, 'package.json');
  const hasProfile = await exists(manifest);
  if (hasProfile) {
    step('检查无头 profile', true, `${profile} 已存在（${pDir}）`);
  } else {
    const base = paths.bundleVersions?.base;
    const headless = paths.bundleVersions?.headless;
    if (!base || !headless) {
      step('创建无头 profile', false, '无法确定 dsh-base / dsh-headless 版本号');
      return { ok: false, error: '无法确定 dsh-base / dsh-headless 版本号，请在 DSH Desktop 中运行本插件', steps, paths };
    }
    const res = await run(paths.node, [paths.dshCli, 'plugin', '--profile', profile, 'add', `@deepseek-ai/dsh-base@${base}`, `@deepseek-ai/dsh-headless@${headless}`], { timeoutMs: 600000 });
    const ok = res.code === 0 && await exists(manifest);
    step('创建无头 profile', ok, ok ? `已创建 ${profile}（bundle ${base}）` : (res.stderr || res.stdout).slice(-300));
    if (!ok) return { ok: false, error: '创建无头 profile 失败（通常是网络或 pnpm 问题）', steps, paths };
  }

  // 3) tick.cmd + vbs
  await writeFile(join(schedDir, 'tick.cmd'), tickCmdBody({ schedDir, dshHome: paths.dshHome, node: paths.node }), 'utf8');
  const vbsPath = join(schedDir, 'hidden-run.vbs');
  step('生成 tick.cmd', true, `${join(schedDir, 'tick.cmd')}`);

  // 4) 计划任务
  let task;
  if (registerTask) {
    task = await schtaskCommand('create', { taskName, vbsPath, intervalMinutes });
    step('注册计划任务', task.ok, task.ok ? `${taskName}（每 ${intervalMinutes} 分钟）` : task.detail ?? task.error);
  } else {
    step('注册计划任务', true, '已跳过（由用户手动配置）');
  }

  return {
    ok: true,
    steps,
    paths,
    profileDir: pDir,
    tickCmd: join(schedDir, 'tick.cmd'),
    vbsPath,
    taskName,
    taskRegistered: Boolean(task?.ok),
    intervalMinutes,
  };
}

/** 移除计划任务并删除运行文件。 */
export async function teardownLocal({ schedDir, taskName = DEFAULT_TASK_NAME, keepFiles = true }) {
  const steps = [];
  const task = await schtaskCommand('delete', { taskName });
  steps.push({ name: '删除计划任务', ok: task.ok, detail: task.detail ?? task.error });
  if (!keepFiles) {
    try {
      await rm(join(schedDir, 'tick.cmd'), { force: true });
      await rm(join(schedDir, 'hidden-run.vbs'), { force: true });
      steps.push({ name: '删除运行入口文件', ok: true, detail: 'tick.cmd / hidden-run.vbs 已删除' });
    } catch (error) {
      steps.push({ name: '删除运行入口文件', ok: false, detail: String(error) });
    }
  }
  return { ok: steps.every((s) => s.ok), steps };
}

/** 本机配置状态（面板显示用）。 */
export async function localStatus({ schedDir, profile = 'headless', taskName = DEFAULT_TASK_NAME }) {
  const paths = await detectPaths();
  const want = await runtimeVersion();
  let have = '';
  try {
    have = (await readFile(join(schedDir, '.runtime-version'), 'utf8')).trim();
  } catch { /* 未安装 */ }
  const task = await schtaskStatus(taskName, paths.node);
  return {
    platform: paths.platform,
    windows: paths.platform === 'win32',
    node: paths.node,
    nodeKind: paths.nodeKind,
    dshCli: paths.dshCli,
    dshHome: paths.dshHome,
    appDir: paths.appDir,
    bundleVersions: paths.bundleVersions,
    profile,
    profileReady: await exists(join(profileDir(paths.dshHome, profile), 'package.json')),
    runtimeVersion: want,
    runtimeInstalled: have === want && have !== '',
    runtimeHave: have || null,
    tickCmd: await exists(join(schedDir, 'tick.cmd')),
    task,
    taskName,
  };
}
